#
# Copyright 2018-present 王用军
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

vxmq:
  rule:
    static:
      ReadMqttPublishFromKafka:
        kafka:
          servers: localhost:9094
        enable: false
      WriteMqttEventToKafka:
        kafka:
          servers: localhost:9094
        enable: false
      WriteMqttEventToMqtt:
        enable: false
  ignite:
    backups: 0
    discovery:
      tcp:
        addresses: localhost:47500
        port: 47500
    work-dir:
  logs:
    level: INFO
  session:
    # Max offline message amount, 0 for no limit.
    queued-message:
      max: 1000
  shell:
    server:
      port: 5000
  mqtt:
    auth:
      # Auth white list, client ids separated by commas
      whitelist: ""
      webhook:
        url: http://localhost:8080/webhook/vxmq/authenticate
      # NONE, WEBHOOK
      type: NONE
    server:
      proxy-protocol:
        enable: false
      port: 1883
  http:
    server:
      port: 8060
  metrics:
    enable: false
