# Copyright (C) 2023-2024 王用军
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

vxmq:
  rule:
    static:
      ReadMqttPublishFromKafka:
        kafka:
          servers: localhost:9094
        enable: false
      WriteMqttEventToKafka:
        kafka:
          servers: localhost:9094
        enable: false
      WriteMqttEventToMqtt:
        enable: false
  ignite:
    backups: 0
    discovery:
      tcp:
        addresses: localhost:47500
        port: 47500
  session:
    # Max offline message amount, 0 for no limit.
    queued-message:
      max: 1000
  shell:
    server:
      port: 5000
  mqtt:
    auth:
      # Auth white list, client ids separated by commas
      whitelist: ""
      webhook:
        url: http://localhost:8080/webhook/vxmq/authenticate
      # NONE, WEBHOOK
      type: NONE
    server:
      proxy-protocol:
        enable: false
      port: 1883
    topic:
      levels:
        max: 128
      alias:
        max: 65535
    message:
      size:
        # 10M
        max: 10485760
    client-id:
      length:
        max: 65535
  http:
    server:
      port: 8060
  metrics:
    enable: false
