version: '3'

services:
  vxmq-kafka:
    image: "bitnami/kafka:3.4"
    container_name: vxmq-kafka
    restart: always
    healthcheck:
      test: [ "CMD", "kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "9094:9094"
    environment:
      # 参考https://hub.docker.com/r/bitnami/kafka和kafka安装包下的config/kraft/server.properties文
      KAFKA_ENABLE_KRAFT: yes
      KAFKA_KRAFT_CLUSTER_ID: D08P23ClSE-M-royJD08IA
      ALLOW_PLAINTEXT_LISTENER: yes
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      KAFKA_CFG_LISTENERS: INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://vxmq-kafka:9092,EXTERNAL://192.168.16.197:9094
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: true
    volumes:
      - vxmq-kafka-volume:/bitnami/kafka
    networks:
      - vxmq

  vxmq-vxmq:
    image: "jpforevers/vxmq:1.5.0"
    container_name: vxmq-vxmq
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8060/api/v1/health | jq -e '.status == \"UP\"'" ]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - "1883:1883"
      - "8060:8060"
      - "5000:5000"
    environment:
      vxmq.rule.static.WriteMqttEventToKafka.enable: true
      vxmq.rule.static.WriteMqttEventToKafka.kafka.servers: vxmq-kafka:9092
      vxmq.rule.static.ReadMqttPublishFromKafka.enable: true
      vxmq.rule.static.ReadMqttPublishFromKafka.kafka.servers: vxmq-kafka:9092
    volumes:
      - vxmq-vxmq-log-volume:/vxmq/logs
      - vxmq-vxmq-ignite-volume:/vxmq/ignite
    networks:
      - vxmq
    depends_on:
      vxmq-kafka:
        condition: service_healthy

volumes:
  vxmq-kafka-volume:
  vxmq-vxmq-log-volume:
  vxmq-vxmq-ignite-volume:

networks:
  vxmq:
