name: vxmq
services:
  vxmq-vxmq1:
    image: "jpforevers/vxmq:latest"
    container_name: vxmq-vxmq1
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8060/q/health | jq -e '.status == \"UP\"'" ]
      interval: 30s
      timeout: 3s
      retries: 5
    environment:
      VXMQ_METRICS_ENABLE: true
      VXMQ_LOGS_LEVEL: DEBUG
      VXMQ_MQTT_SERVER_PROXY_PROTOCOL_ENABLE: true
    networks:
      - vxmq

  vxmq-vxmq2:
    image: "jpforevers/vxmq:latest"
    container_name: vxmq-vxmq2
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8060/q/health | jq -e '.status == \"UP\"'" ]
      interval: 30s
      timeout: 3s
      retries: 5
    environment:
      VXMQ_METRICS_ENABLE: true
      VXMQ_LOGS_LEVEL: DEBUG
      VXMQ_MQTT_SERVER_PROXY_PROTOCOL_ENABLE: true
    networks:
      - vxmq

  vxmq-vxmq3:
    image: "jpforevers/vxmq:latest"
    container_name: vxmq-vxmq3
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl --fail http://localhost:8060/q/health | jq -e '.status == \"UP\"'" ]
      interval: 30s
      timeout: 3s
      retries: 5
    environment:
      VXMQ_METRICS_ENABLE: true
      VXMQ_LOGS_LEVEL: DEBUG
      VXMQ_MQTT_SERVER_PROXY_PROTOCOL_ENABLE: true
    networks:
      - vxmq

  vxmq-haproxy:
    image: "haproxy:2.8"
    container_name: vxmq-haproxy
    restart: always
    healthcheck:
      test: [ "CMD", "haproxy", "-c", "-f", "/usr/local/etc/haproxy/haproxy.cfg" ]
      interval: 30s
      timeout: 5s
      retries: 3
    ports:
      - "9999:9999"
      - "1883:1883"
      - "8060:8060"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg
    networks:
      - vxmq
    depends_on:
      vxmq-vxmq1:
        condition: service_healthy
      vxmq-vxmq2:
        condition: service_healthy
      vxmq-vxmq3:
        condition: service_healthy

networks:
  vxmq:
